openapi: 3.2.0
info:
  title: FlowPay Construction API
  version: 2.0.0-alpha.4
  description:
    $ref: docs/general.md
  termsOfService: https://developer.flowpay.it/tos
  license:
    name: FlowPay SRL
    url: https://developer.flowpay.it/tos
  x-logo:
    url: https://images.flowpay.it/logo
    altText: FlowPay
  contact:
    name: API Support
    url: https://developer.flowpay.it
    email: api-support@flowpay.it
  x-json-schema-faker:
    locale: it-IT
    omitNulls: true
    fillProperties: true
    reuseProperties: true
servers:
- url: https://api.flowpay.it/v2
  description: Production server (Not implementend)
- url: https://mock.flowpay.it/v2
  description: Mock server
- url: https://sandbox.{customerID}.flowpay.it/v2
  description: Customer-assigned sandbox server
  variables:
    customerID:
      default: 00000000-00000000-00000000-00000000
      description: Unique customer identifier assigned after contract signature
- url: http://localhost:5002
  description: Debug
tags:
- name: Construction
  description: Manage construction sites and related entities lifecycle
paths:
  /constructions/contracts:
    post:
      tags:
      - Construction
      operationId: addSiteWorker
      summary: Add worker to site
      description: This endpoint manages the association between a site and a worker. Is not mandatory for the worker to be registered on FlowPay. This request must be authorized by the site owner, then the worker will be able to call the [PATCH] `/constructions/contracts/{identifier}` endpoint to complete the handshake.
      security:
      - oAuth2:
        - construction:write
    get:
      tags:
      - Construction
      operationId: getWorkers
      summary: List workers
      description: Allows to retrieve a list of workers associated to the customer.
      security:
      - oAuth2:
        - construction:read
  /constructions/contracts/{identifier}:
    patch:
      summary: Accept assignment
      description: This endpoint allows workers to accept the assignment to a site. The request must be authorized by the worker.
      operationId: acceptSiteAssignment
      security:
      - oAuth2:
        - construction:write
      tags:
      - Construction
    delete:
      summary: Contract withdrawal
      description: This endpoint allows workers and site owners to withdraw from a contract. The request must be authorized by the worker or the site owner.
      operationId: withdrawFromSite
      security:
      - oAuth2:
        - construction:write
      tags:
      - Construction
  /constructions/sites:
    post:
      tags:
      - Construction
      operationId: createConstructionSite
      summary: Open a new site
      description: Allows to define a new site to be managed with FlowPay
      security:
      - oAuth2:
        - authorization_code
    get:
      tags:
      - Construction
      operationId: getConstructionSites
      summary: List sites
      description: Allows to retrieve a list of sites managed by the customer
      security:
      - oAuth2:
        - construction:read
  /constructions/sites/{identifier}:
    get:
      tags:
      - Construction
      operationId: getConstructionSite
      summary: Get site details
      description: Allows to retrieve details of a specific site
      security:
      - oAuth2:
        - construction:read
  /constructions/sites/{identifier}/quote:
    post:
      tags:
      - Construction
      operationId: createQuote
      summary: Create quote
      description: 'Allows to create a new quote for a specific site, useful to credit site owner wallet with the amount needed to start the site operations.

        The request must be authorized by the site owner.'
      security:
      - oAuth2:
        - construction:write
        - wallet:construction
    get:
      tags:
      - Construction
      operationId: getQuotes
      summary: List quotes
      description: Allows to retrieve a list of quotes for a specific site
      security:
      - oAuth2:
        - construction:read
        - wallet:construction
  /constructions/progress:
    post:
      summary: Register work progress
      description: 'You can register work progress by passing a list of the invoices previously uploaded using the `/invoices` endpoint.

        The request must be authorized by the worker.

        Each invoice between site owner and worker will be linked to a new site-related document.

        Each invoice between the worker and their suppliers will be linked to a new document.

        Note: The sum of the worker-to-customer invoices must be at least equal to the sum of the supplier-to-worker invoices.'
      operationId: registerWorkProgress
      security:
      - oAuth2:
        - construction:write
      tags:
      - Construction
    get:
      summary: List work progress
      description: Allows to retrieve a list of work progress registered by the worker
      operationId: getWorkProgress
      security:
      - oAuth2:
        - construction:read
      tags:
      - Construction
  /constructions/progress/{identifier}:
    get:
      summary: Get work progress details
      description: Allows to retrieve details of a specific work progress
      operationId: getWorkProgressDetails
      security:
      - oAuth2:
        - construction:read
      tags:
      - Construction
components:
  securitySchemes:
    oAuth2:
      type: oauth2
      description: OAuth2 flow
      flows:
        authorizationCode:
          authorizationUrl: /openid/authenticate
          tokenUrl: /oauth/token
          refreshUrl: /oauth/token
          scopes:
            accounts:read: Allow to read accounts
            accounts:write: Allow to mediate accounts creation and open banking consent renewal
            invoices:read: Allow to read invoices
            invoices:write: Allow to create invoices and manage lifecycle
            bills:read: Allow to read bills
            bills:write: Allow to create bills and manage lifecycle
            constructions:read: Allow to read information about construction sites
            constructions:write: Allow to create construction sites and manage the lifecycle
            openid: Allow to read user profile
            pagopa:read: Allow to retrieve users' PagoPA payment notices
            pagopa:write: Allow to create PagoPA payment notices
            transfers:read: Allow to read transfers
            transfers:write: Allow to create transfers and manage lifecycle
            wallet:`document_type`: Allow to manage wallet for the specified use case
        clientCredentials:
          tokenUrl: /oauth/token
          scopes:
            ade: Allow to interact with Agenzia delle Entrate services
            accounts:read: Allow to read accounts
            accounts:write: Allow to mediate accounts creation and open banking consent renewal
            invoices:read: Allow to read invoices
            invoices:write: Allow to create invoices and manage lifecycle
            bills:read: Allow to read bills
            bills:write: Allow to create bills and manage lifecycle
            constructions:read: Allow to read information about construction sites
            constructions:write: Allow to create construction sites and manage the lifecycle
            openid: Allow to read user profile
            pagopa:read: Allow to retrieve users' PagoPA payment notices
            pagopa:write: Allow to create PagoPA payment notices
            transfers:read: Allow to read transfers
            transfers:write: Allow to create transfers and manage lifecycle
            wallet:`document_type`: Allow to manage wallet for the specified use case
